ISPP-2425-G4/borroo

- .github/workflows/test.yml
- backend/pytest.ini
- backend/requirements.txt
- frontend/.gitignore
- frontend/package-lock.json
- frontend/package.json
- Configurado GitHub Actions para CI/CD
- Agregados archivos .gitkeep en tests/ para rastrear carpetas vacías
- Ignorados archivos de caché (__pycache__, *.pyc) en .gitignore
- Instaladas dependencias necesarias en frontend y backend
- Configurada Vitest para pruebas en frontend
- Configurada pytest en backend
> Setup del entorno de pruebas unitarias en backend y frontend

- .github/workflows/commits.yml
Issue: Implementar workflow de política de commits
[#33](https://github.com/ISPP-2425-G4/borroo/issues/33)
> Implementar workflow de política de commits

- backend/borroo/settings.py
- backend/usuarios/apps.py
- backend/usuarios/models.py
- backend/usuarios/serializers.py
- backend/usuarios/urls.py
- backend/usuarios/views.py
También incluye el desarrollo de funcionalidades CRUD asociadas a usuarios
> Implementar entidad User

- frontend/src/CreateItem.jsx
- frontend/src/ShowItem.jsx
- frontend/src/UpdateItem.jsx
Arreglada la conexión con el backend
> Bug - Fallo en la url del frontend a la hora de crear un objeto

- backend/usuarios/urls.py
- backend/usuarios/views.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/CreateItem.jsx
- frontend/src/SignUp.jsx
Adicionalmente se ha añadido al campo de pais un selector de paises con autocompletado.
> Validadores frontend de registro

- backend/objetos/views.py
- frontend/src/Layout.jsx
- frontend/src/ShowItem.jsx
Se ha añadido un botón en la pestaña de detalles de un item que permite destacar el objeto si el usuario tiene el plan premium. Entonces, al redirigirse a la pagina principal, sale la pestaña de objetos destacados
> Frontend productos destacados

- backend/rentas/views.py
Ahora se puede hacer una renta si se ha cancelado una comprobar en:
> feat: Arreglado deja hacer rentas si se ha cancelado

- frontend/src/Navbar.jsx
Se ha cambiado la condición a comprobar para mostrar el botón de Dashboard, antes comprobaba el nombre de usuario, ahora comprueba que es un administrador.
> BUG: Verificar que un usuario es administrador

- frontend/src/CreateItem.jsx
- frontend/src/CreateItemRequest.jsx
Se ha arreglado la flecha de política de cancelación de los formularios de crear ítem y de crear un anuncio
> Arreglo frontend politica de cancelación

- backend/usuarios/models.py
- backend/usuarios/serializers.py
- backend/usuarios/views.py
Añadido atributo para usuarios de cif para empresas, el usuario se verificara si tiene cif y dejara se serlo si se lo quita, ademas de que el cif debe seguir la estructura de los cif en España(una letra, 7 numeros y un número/letra de control)
> Backend perfil de empresa

- frontend/src/CreateItem.jsx
Ahora al guardar un objeto en borradores te redirige a tus borradores
> BUG: Redirección tras guardar como borrador

- backend/usuarios/views.py
- frontend/src/Login.jsx
Ahora se puede iniciar sesion tanto con el username como con el email
> Full stack inicio de sesion

- frontend/src/Navbar.jsx
Se ha añadido el logo en el navbar y se ha quitado el icono del carrito.
> Añadir el logo en el navbar y quitar el boton del carrito

- backend/pagos/views.py
- backend/rentas/views.py
- backend/usuarios/views.py
- frontend/src/RentRequestBoard.jsx
- frontend/src/components/RequestCardsContainer.jsx
El estado de aceptado o rechazado para ambas personas ya salen en las solicitudes. Está pendiente hacer un trackeo completo, pero esto ya funciona.
> BUG: Trackear las solicitudes

- frontend/src/Layout.jsx
La búsqueda ya es case sensitive. Por ejemplo, aparecen los mismos resultados si se busca "padel" y "pádel"
> BUG: La búsqueda no es case insensitive

- frontend/index.html
- frontend/src/Layout.jsx
- frontend/src/components/AdSense.jsx
- frontend/src/components/AdSenseMock.jsx
Se añadieron anuncios al listado de objetos. actualmente son de prueba porque en localhost no se muestran, deben cambiarse para el despliegue
> Full stack de añadir los anuncios publicitarios

- frontend/public/styles/Modal.css
- frontend/src/Modal.jsx
- frontend/src/RentRequestBoard.jsx
- frontend/src/ShowItem.jsx
- frontend/src/components/ConfirmModal.jsx
- frontend/src/components/SuccessModal.jsx
Creado el popup cuando se solicita un objeto que le permite redigir al usuario al apartado de "Mis solicitudes"
> Popup al solicitar un objeto

- backend/objetos/serializers.py
- frontend/src/Layout.jsx
Se ha modificado serializers de objetos y el Layout para que salga la ubicación de la ciudad del usuario en cada paquete de cada objeto en la vista de la pagina principal, además de que vaya saliendo la valoración media que va teniendo el usuario
> Las valoraciones de los usuarios visualmente en el catalogo

- backend/rentas/views.py
- frontend/src/Profile.jsx
Corregido que las reseñas ahora solo se puedan hacer cuando se pague el alquiler de un objeto a un usuario.
> Frontend de editar un perfil

- backend/objetos/models.py
- backend/objetos/views.py
- backend/tests/unit/test_crud_ask_for_a_rent.py
- backend/tests/unit/test_search_items.py
He corregido dos tests del subgrupo 1 que antes no pasaban
> Creación de pruebas unitarias y test faltantes subgrupo1

- frontend/src/Layout.jsx
Corregido bug causado por conflictos en filtro "Favoritos"
> fix: Corregido bug filtro favoritos

- backend/usuarios/models.py
- frontend/src/Profile.jsx
Para estar identificado necesitas tener DNI o ser una cuenta de empresa
> Arreglo DNI y cuenta empresa

- backend/tickets/models.py
- backend/tickets/serializers.py
- backend/tickets/urls.py
- backend/tickets/views.py
- frontend/src/AdminTicketsDashboard.jsx
- frontend/src/App.jsx
- frontend/src/Navbar.jsx
- frontend/src/TicketDetail.jsx
> Panel de administrador para poder ver las incidencias de los alquileres

- backend/tests/performance/locustfile_recuperacion_contraseña.py
> Generación de pruebas de carga para operaciones de recuperación de contraseña

- backend/objetos/serializers.py
- frontend/src/ListItemRequests.jsx
En los anuncios de objetos ya se muestra la ubicacion del usuario que lo crea.
> Añadir ubicación en la publicación de anuncios

- backend/tests/e2e/test_login/test_login_fail.py
- backend/tests/e2e/test_login/test_login_success.py
Añadido test de selenium exitoso y test de selenium erróneo del login
> Testing para pruebas E2E

- docs/PPL/pilotUsersPerformanceEvaluation.md
Se ha cambiado la calificacion final de los UP
> fix: Arreglado calificación de usuarios piloto final
